resources:
- name: concourse-git
  type: git
  source:
    uri: https://github.com/chhhavi/onboarding-week.git
    branch: master

jobs:
- name: raisins
  plan:
  - get: concourse-git
    trigger: true
  - task: taste-bad
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      run:
        path: echo
        args: ["I'm disgusting"]
