resources:
- name: concourse-git
  type: git
  source:
    uri: https://github.com/chhhavi/onboarding-week.git
    branch: master

jobs:
- name: raisins
  plan:
  - get: concourse-git
    trigger: true
  - task: taste-bad
    file: tasks/taste-bad/task.yml
